### ISSUE TITLE
Angular >2.X issue with href fragments

### ISSUE THREAD

**Issue by flamusdiu** [jonschlinkert/markdown-toc#104]
With Angular, I cannot seem to use just the `#frag` href references. I need to use `myComponent#frag` instead. I don't see a way to add these to the generated URLs unless I completely parse the generated JSON. 

I guess this might be expected but not shown in any of the information. Also, there is an issue with href routing noted angular/angular#6595 -- for those using this in Angular >2.X projects.

**Comment by doowb** [comment]
I'm going to close this because I think I've addressed how you can use the `linkify` option in #106 to achieve what you need to work with angular.

**Comment by flamusdiu** [comment]
@doowb yeah, I was more or less trying to document the issue with Angular. Not really sure how many people have ran across the issue when dealing with `markdown-toc` (or other libraries).
