### ISSUE TITLE
npm install fails because of coffee-script (dependency of gray-matter) postinstall script

### ISSUE THREAD

**Issue by mgroenhoff** [jonschlinkert/markdown-toc#107]
I can no longer install markdown-toc^1 because gray-matter^2 has a dependency (note: no dev-dependency) on coffee-script^1 which now resolves to the recently published 1.12.8 which fails to install because they added a postinstall script that fails (it forces you to change to coffeescript, without the "-" in between). 1.12.7 Does not have this postinstall script.
gray-matter already contains an issue (https://github.com/jonschlinkert/gray-matter/issues/55) for this but since its latest version is 3.1.1 this must be back ported to 2. gray-matter 3.1.1 has moved coffee-script (still wrong) to its dev-dependencies this version can be used.

So basically this leaves two options: A update to gray-matter^3 or B, wait until gray-matter is updated to fix this (and back port it to v2).

**Update:** The reason the postinstall script failed was not because it was designed to do so, it should just show a warning about switching to coffeescript but because of some sort of syntax error. See https://github.com/jashkenas/coffeescript/issues/4805 .

References:
https://github.com/jonschlinkert/markdown-toc/blob/1.2.0/package.json
https://github.com/jonschlinkert/gray-matter/blob/2.1.1/package.json
https://github.com/jonschlinkert/gray-matter/blob/3.1.1/package.json
https://github.com/jashkenas/coffeescript/blob/1.12.8/package.json

**Comment by doowb** [comment]
@mgroenhoff thanks for digging into this. I saw some of the issues on gray-matter and followed the references through vue-cli and into coffeescript. It looks like the issue has been fixed at the source (e.g. the coffeescript module changed how they're showing that warning).

Could you try installing `markdown-toc` again to verify that this is fixed? I'll look into updating gray-matter to version 3 here so coffee-script doesn't get installed.

**Comment by mgroenhoff** [comment]
We currently use my fork in our development setup so it is installing fine. coffee-script is not installed when gray-matter v3 is used because it is a dev-dependency. It was regular dependency in v2. You could however update both v3 and v2 to refer to coffeescript instead of coffee-script to prevent warnings to show up when installing.

**Comment by mgroenhoff** [comment]
This is no longer an issue because coffee-script unpublished v1.12.8. They're still working on showing the deprecation warning on installation though.
