### ISSUE TITLE
TocProvider.slugify is not a function

### ISSUE THREAD

**Issue by wayneashleyberry** [jonschlinkert/markdown-toc#113]
I installed the Markdown Extras today and tried adding a table of contents to an existing markdown file but got the following error:

> TocProvider.slugify is not a function

**Version 1.21.0-insider (1.21.0-insider)**

**Comment by doowb** [comment]
@wayneashleyberry can you provide more information, a code example on how you're using `markdown-toc`, and links to some of the things you mentioned above?

I don't know what "Markdown Extras" is, but it seems that this should be an issue for that.

**Comment by wayneashleyberry** [comment]
I'm terribly sorry, it seems I opened this issue on the wrong repo! It should have been on https://github.com/neilsustc/vscode-markdown
