### ISSUE TITLE
markdown-toc module not supported with webpack

### ISSUE THREAD

**Issue by zainimran** [jonschlinkert/markdown-toc#115]
Webpack compiles fine but in the console this I get this error:
'amd-define.js:1 Uncaught Error: define cannot be used indirect'

It could be something to do with the lazy cache

**Comment by doowb** [comment]
Use [unlazy-loader](https://github.com/doowb/unlazy-loader) if you think it's a lazy-cache issue. This has been mentioned in other issues in this repository.
