### ISSUE TITLE
npm WARN deprecated coffee-script@1.12.7

### ISSUE THREAD

**Issue by simonhaenisch** [jonschlinkert/markdown-toc#120]
After installing I get

> npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)

because the gray-matter dependency is still on 2.x (even though it was upgraded in 797e820fc24e08085e1e71646110b8c92cc56c18).

Can you please tag a new release for NPM?

**Comment by doowb** [comment]
thanks for the reminder. There are a couple of other things to do then I'll publish this.

**Comment by bguggie** [comment]
did you ever publish a release with the update `gray-matter` dependency?
