### ISSUE TITLE
CoffeeScript on NPM has moved to "coffeescript" (no-hyphen) & Removed event-stream from gulp-header

### ISSUE THREAD

**Issue by salmonjean** [jonschlinkert/markdown-toc#147]
Hi Mister,

I've tried to install markdown-toc, without success. 
Here are the two warning messages :

![markdown-toc - CoffeeScript on NPM has moved](https://user-images.githubusercontent.com/53435419/62854893-f16aec00-bcf0-11e9-825d-8bf9cd4ecd32.jpg)

Thanks for your help.

Regards,

Jean Salmon

**Comment by doowb** [comment]
Hi Jean,

Those are just warning messages so `markdown-toc` should have still installed (it just didn't install globally).

Use the following command to install globally:

```sh
npm install markdown-toc --global
```

Then you should be able to use your command:

```sh
markdown-toc input.md
```

The README.md needs to be updated with this information (I think there's already a PR to do that so I'm going to close this issue).

Thanks for the issue and feel free to open a new issue if you run into any bugs.

**Comment by salmonjean** [comment]
Hi Brian,

Thanks a lot for your help! Now it works! :-)
How to number the titles please?

See You!

Jean

PS : I've never been to Boston neverthelless I saw the Red Sox playing in the Yankee Stadium 7 years ago, great memories! ;-)

**Comment by doowb** [comment]
> How to number the titles please?

You probably want to take a look at using `markdown-toc` through the API. Specifically see the [JSON](https://github.com/jonschlinkert/markdown-toc#tocjson) object that's returned from calling the `toc` function.

I'm just a Red Sox fan 😀 I've only been to Boston once but have never had a chance to see a live game.

**Comment by salmonjean** [comment]
Hi Brian!
Thanks for your answer nevertheless perhaps I've not been clear enough.

For context, first I have to convert several word documents to gfm markdown (keeping titles styles). I'm already using md-to-pdf (https://www.npmjs.com/package/md-to-pdf) to convert gfm markdown files to pdf. With the right CSS, I'm able to number each titles.
The markdown files will then be the reference (in order to not use anymore word documents).

From  markdown files, I need to be able to generate a table of contents after each update inside.
Your _**markdown-toc**_ works fine for generating table of contents with bullets.
Instead of bullets, how to number titles please ?
(like https://github.com/AlanWalk/markdown-toc#32-insert-header-number-sections for instance).
Do not hesitate to submit a workaround eventually! 
Thank You!

P.S. : I wish you to see the Red Sox playing in live one day ! ;-)

**Comment by doowb** [comment]
> how to number titles please

Try using `'1.'` for the `bullets` option.

If that doesn't work, then I think a PR to allow passing a customization function to [list-item](https://github.com/jonschlinkert/list-item/) would be useful. `list-item` is the library that handles generating each item in the TOC.

**Comment by salmonjean** [comment]
Hi Brian,
Even if it was not what I expected exactly,  it's already better!
Thanks for your help! ;-)
