### ISSUE TITLE
Allow for multiple input files when -i is specified

### ISSUE THREAD

**Issue by Lucas-C** [jonschlinkert/markdown-toc#162]
Would you be open for this slight extension of this tool current command line interface ?

If so, I would be willing to submit a PR

This has been requested from users of this tool as a git pre-commit hook: https://github.com/Lucas-C/pre-commit-hooks-nodejs/issues/8

**Comment by beliaev-maksim** [comment]
Hi @doowb , @jonschlinkert 
could this feature be considered?

if yes, we can propose a PR

**Comment by jonschlinkert** [comment]
Sure I’d be happy to consider. A PR for discussion would be great

**Comment by Lucas-C** [comment]
I opened https://github.com/jonschlinkert/markdown-toc/pull/172
