### ISSUE TITLE
Cannot find module 'remarkable' at webpackEmptyContext (eval at ./node_modules/_markdown-toc@1.2.0@markdown-toc/lib sync recursive

### ISSUE THREAD

**Issue by longwayya** [jonschlinkert/markdown-toc#165]
This problem appeared in my Vue project. I don't know how everyone solved it. I think it's probably a matter of version. I found a node_modules folder in the NPM package. I don't know how.

In short, please forgive my ignorance.

**Comment by enricofer** [comment]
same issue here

**Comment by enricofer** [comment]
There are issues with webpack and lazy-loader module https://github.com/jonschlinkert/markdown-toc/issues/115
I solved installing the unlazified version gratefully provided by an unknown user :https://www.npmjs.com/package/markdown-toc-unlazy

**Comment by longwayya** [comment]
cool
