### ISSUE TITLE
Q: Can this be used as a remarkable plugin ?

### ISSUE THREAD

**Issue by tgeens** [jonschlinkert/markdown-toc#27]
The `generate` function sets this up as a remarkable plugin internally, but is not exported.

Is it possible to use this directly as a remarkable plugin ?

**Comment by tgeens** [comment]
Hmm, after closer inspection I don't think it makes a lot of sense.

The `generate` function is a plugin that replaces the Remarkable renderer to render the TOC for a given md-string.

I was more looking for a remarkable-plugin that would inline-replace the `<!-- toc -->` marker.

Would that even be possible with the remarkable ?

**Comment by jonschlinkert** [comment]
> Hmm, after closer inspection I don't think it makes a lot of sense.

As a remarkable plugin, you're right.  I use this to generate TOCs for [verb](https://github.com/assemble/verb) and intended to split out the plugin but got busy and decided it was better to just push it up than keep sitting on it. the plan was to publish `remarkable-toc` as a plugin that would inline the TOC as you're suggesting. 

> Would that even be possible with the remarkable ?

definitely. to clarify though, do you want the rendered document to be markdown or HTML? it's doable either way.

**Comment by tgeens** [comment]
The way markdown-pdf works now is it renders md.

But in the end - as a remarkable plugin - I would expect it to generate HTML ?

**Comment by jonschlinkert** [comment]
> I would expect it to generate HTML ?

K, makes sense. if I get some time I can do a remarkable-toc plugin that renders HTML. fwiw, since the vast majority of documentation I work with is in markdown format, I've always found it to be much easier to generate the TOC as markdown. that way you can use whatever conventions you want for converting your markdown to html and everything will be consistent. not sure if that makes sense how I explained it...

**Comment by tgeens** [comment]
The TOC as md makes sense and is in the end more flexible.

But in the context of a remarkable-plugin, I would expect it to render some predefined markup (like the insert  marker) as html ?

If you want md-output, this project does that very well ?

**Comment by jonschlinkert** [comment]
> I would expect it to render some predefined markup (like the insert  marker) as html ?

noted, I'll let you know if I publish one that does HTML or add that as a feature. should't be too difficult

**Comment by dotmagic** [comment]
I use it with markdown-pdf using the preProcessMd argnument, works fine for me but I'm sure there's a better way to do it.
