### ISSUE TITLE
Awkward formatting in README.md

### ISSUE THREAD

**Issue by pdehaan** [jonschlinkert/markdown-toc#29]
I noticed that the contents in [toc.insert](https://github.com/jonschlinkert/markdown-toc#tocinsert) look a bit "off" but they look fine in the .verb.md file...

### README.md:
```
### toc.insert

Insert a table of contents immediately after an _opening_ `

` code comment, or replace an existing TOC if both an _opening_ comment and a _closing_ comment (`

`) are found.
```

### .verb.md:
```
### toc.insert

Insert a table of contents immediately after an _opening_ `<!-- toc -->` code comment, or replace an existing TOC if both an _opening_ comment and a _closing_ comment (`<!-- tocstop -->`) are found.
```

Looks like somewhere in the verb->readme formatting, the HTML comments are getting parsed and stripped.

**Comment by jonschlinkert** [comment]
Good catch, thanks! looks like I added an extra backtick somewhere, or one too few...

**Comment by jonschlinkert** [comment]
fixed thanks!
