### ISSUE TITLE
Custom slugify

### ISSUE THREAD

**Issue by disharmonized** [jonschlinkert/markdown-toc#30]
I have a cyrillic symbols in headings and markdown-toc slugifying them into sequence of -----. 
There are npm module transliteration.cyr, that converts cyrillic symbols into latin, but i can not use it because there is no custom slugifying support. It would be nice, if you will add it or share another solution.

**Comment by jonschlinkert** [comment]
You should be able to pass a custom slugify function on the options. have you tried it?

**Comment by disharmonized** [comment]
No, cause i dont know how to do that. Remarkable does not have any certain documentation how to do that. It would be very nice if you show me any example, please.

**Comment by jonschlinkert** [comment]
It's on the readme

**Comment by jonschlinkert** [comment]
sorry I was on my iphone at the time, I was wrong. Looks like I only have it documented locally. I'll add docs to the readme and link back.

**Comment by disharmonized** [comment]
Thank you, i will waiting for it!
