### ISSUE TITLE
`toc` adds extra newlines each time it is run

### ISSUE THREAD

**Issue by RichardBradley** [jonschlinkert/markdown-toc#34]
I have found that `toc` adds extra newlines to my README each time it is run.
This means that I can't add it as a build step.

I think that running `toc` multiple times on the same file should not result in any changes, i.e. it should be idempotent.

Repro at https://gist.github.com/RichardBradley/a72c644e0e09eb501f1f

**Comment by jonschlinkert** [comment]
sounds like a bug. thanks for reporting

**Comment by RichardBradley** [comment]
Sorry, this bug belongs on https://github.com/jonschlinkert/marked-toc not here.

I can't get `markdown-toc` to edit my README inline from the cli, so I can't retest if this bug also belongs here.

**Comment by RichardBradley** [comment]
This does not appear to happen in `markdown-toc` -- it's an old bug in `marked-toc`.

> I can't get markdown-toc to edit my README inline from the cli, so I can't retest if this bug also belongs here.

See #37
