### ISSUE TITLE
`toc` strips newline from end of file

### ISSUE THREAD

**Issue by RichardBradley** [jonschlinkert/markdown-toc#35]
Traditionally, text files should end with a newline char.

The `toc` command strips the trailing newline from a README which has one.

I think that `toc` should either not change the presence or absence of a trailing newline, or if it does want to take an opinion on this issue, it should add one rather than remove one.

**Comment by RichardBradley** [comment]
Sorry, this bug belongs on https://github.com/jonschlinkert/marked-toc not here.

I can't get `markdown-toc` to edit my README inline from the cli, so I can't retest if this bug also belongs here.

**Comment by RichardBradley** [comment]
> I can't get markdown-toc to edit my README inline from the cli, so I can't retest if this bug also belongs here.

I have now tested this (see #37), and `markdown-toc` has the same bug.

Please could you reopen?

**Comment by jonschlinkert** [comment]
Sorry I don't think i meant to close this one. my mistake.

**Comment by RichardBradley** [comment]
Thanks!

**Comment by jonschlinkert** [comment]
thank you! sorry it took so long. Once I get behind (from a cold) it seems like it takes forever to catch back up!
