### ISSUE TITLE
toc generates no unique links for repeating headers

### ISSUE THREAD

**Issue by mcpride** [jonschlinkert/markdown-toc#36]
Example:

```
# Header 1

## Description
blabla

## Examples
blabla

# Header 2

## Description
blabla

## Examples
blabla
```

In this example the sub headers of "Header 2" must get a numbered suffix in its link separated with a "-".

The resulting toc should look like:

```
- [Header 1](#header-1)
    - [Description](#description)
    - [Examples](#examples)
- [Header 2](#header-2)
    - [Description](#description-1)
    - [Examples](#examples-1)
```

**Comment by jonschlinkert** [comment]
Can't believe I haven't experienced that yet.  thanks for reporting.

**Comment by RichardBradley** [comment]
I've run into this too.

It looks like GitHub automatically adds "-1" to the anchors, so `markdown-toc` should do the same.
See e.g. https://gist.github.com/RichardBradley/f0016393755f548d2b10#examples-1

**Comment by jonschlinkert** [comment]
Yeah I did this with a browser implementation somewhere. shouldn't be too difficult.
