### ISSUE TITLE
Add CLI option to add toc to existing file

### ISSUE THREAD

**Issue by RichardBradley** [jonschlinkert/markdown-toc#37]
The https://github.com/jonschlinkert/marked-toc project had a command-line option to update the table of contents of a markdown file inline (i.e. to apply `toc.insert` to a named file).

This would be very useful in `markdown-toc`

**Comment by jonschlinkert** [comment]
good idea, I can add this the next time I make changes, unless you or someone else wants to do a pr in the meantime. thanks

**Comment by RichardBradley** [comment]
I just did one -- sorry, I should have pointed that out.
I thought Github would magically link the two, but it doesn't seem to have done so -- it's #38

**Comment by jonschlinkert** [comment]
awesome, thanks! I would have seen it in a couple of minutes anyway - I just started going through issues. reviewing now
