### ISSUE TITLE
Sections with "-" in the title don't link correctly

### ISSUE THREAD

**Issue by RichardBradley** [jonschlinkert/markdown-toc#40]
I have a README with a section with a "-" in the title:

    # Development - IntelliJ

The link generated by `markdown-toc` looks like:

    https://github.com/me/myproject#development-intellij

But the link generated by GitHub when it renders the README needs to look like 

    https://github.com/me/myproject#development---intellij

**Comment by jonschlinkert** [comment]
I think I know the right way to slugify this now. I can update when merge your pr - probably today. thanks

**Comment by jonschlinkert** [comment]
let me know if this doesn't work for you.
