### ISSUE TITLE
Usage with webpack

### ISSUE THREAD

**Issue by BarryThePenguin** [jonschlinkert/markdown-toc#44]
I've had success in the past using this module with webpack. I'm not sure when or which version the change occurred, but this is no longer the case.

I've setup a [gist](https://gist.github.com/BarryThePenguin/43f694557ce8c6701474) with the bare minimum code showing what I've been doing.

Output from webpack
```
WARNING in ./~/markdown-toc/lib/utils.js
Critical dependencies:
7:34-41 require function is used in a way in which dependencies cannot be statically extracted
 @ ./~/markdown-toc/lib/utils.js 7:34-41
```

Output from browser
```
bundle.js:10939 Uncaught Error: Cannot find module 'remarkable'.
```

I have tried `process.env.UNLAZY = true;` as suggested in `lazy-loader`
This results in a failure to resolve minimist

I have tried [doowb/unlazy-loader](https://github.com/doowb/unlazy-loader)
Though as I'm using babel on my own source files, I can't use `unlazy-loader` without running babel across all my `node_modules` which takes a _long_ time.

I have tried using unlazy in my import statement
```js
import toc from '!unlazy!markdowntoc';
```
This results in just `markdown-toc/index.js` being resolved with unlazy.

I understand there are a lot of parties involved here, so I thought I'd start here and hopefully involve others as the need arises.

These were the two related issues I found
jonschlinkert/lazy-cache#3
webpack/webpack#1763

**Comment by doowb** [comment]
Adding these sections to the `webpack.config.js` work fine for me:

```js
  // this is required because `gray-matter` uses the `fs` module for some things
  node: {
    fs: "empty"
  },
```

As the last loader:

```js
, {
      test: /\.js$/,
      loaders: ['unlazy']
    }
```

This will work because you've already transformed your scripts through babel, now the unlazy loader will work on anything other javascript that's required through a `require` statement. No need to transform the entire `node_modules` with babel. Also, `unlazy-loader` will return quickly when it detects that the file doesn't need to be transformed, so this is a lot faster than the babel transforms.

**Comment by BarryThePenguin** [comment]
Ah! Thank you @doowb!

In addition to the last loader, I added an include regex so unlazy is only applied to the `markdown-doc` directory.

```js
{
    test: /\.js$/,
    loaders: ['unlazy'],
    include: /node_modules\/markdown-toc/
}
```

It didn't help that I have two sets of loaders, dev and prod, and unlazy was only being used by prod. But oh well...

Thanks again!

**Comment by devuxer** [comment]
For those using Create-React-App, this is not really a solution (since we don't have any direct way to modify webpack.config.js).

Is there any way this could be fixed properly (without having to touch webpack), and if yes, would you consider re-opening this issue?

**Comment by mdddj** [comment]
https://github.com/jonschlinkert/markdown-toc/issues/44#issuecomment-462670958
我遇到了这个问题，请问怎么解决的？

**Comment by kurikomoe** [comment]
> [#44 (comment)](https://github.com/jonschlinkert/markdown-toc/issues/44#issuecomment-462670958)
> 我遇到了这个问题，请问怎么解决的？

maybe you can use [https://www.npmjs.com/package/markdown-toc-unlazy](https://www.npmjs.com/package/markdown-toc-unlazy) as alternative
