### ISSUE TITLE
Q: How does insert work?

### ISSUE THREAD

**Issue by marcoms** [jonschlinkert/markdown-toc#45]
From the Readme I can't tell what it is (function?) or how to use it, am I missing something? I'll look in the source for now but perhaps it could be documented better?

**Comment by jonschlinkert** [comment]
see https://github.com/jonschlinkert/markdown-toc/blob/master/cli.js#L40

**Comment by jonschlinkert** [comment]
closing based on age and since it's addressed in the docs
