### ISSUE TITLE
Slugs for underscores in headlines is wrong

### ISSUE THREAD

**Issue by dvcrn** [jonschlinkert/markdown-toc#51]
Looks like I found another edgecase :) 

```
# main:hello_world
```

renders to
```
- [main:hello_world](#mainhello-world)   
```

instead of
```
- [main:hello_world](#mainhello_world)   
```

Again, as a result the anchor link doesn't match with the github generated one

**Comment by jonschlinkert** [comment]
thanks, want to do a pr?

**Comment by dvcrn** [comment]
Might give it a try tomorrow if I find some free time :) if you can solve it before that - great!

**Comment by dvcrn** [comment]
Hi, I submitted the PR. Any chance this can get merged soon? 😄

**Comment by jonschlinkert** [comment]
Thanks I'll review as soon as I get a chance
