### ISSUE TITLE
Slugs for "`" is wrong, lol

### ISSUE THREAD

**Issue by tunnckoCore** [jonschlinkert/markdown-toc#55]
Noticed it before few mins.

having this heading

# `API`

it generates

```md
- [`API`](#-api-)
```

but the link should be `#api` only, not `#-api-`

working example

```js
'use strict'

var toc = require('markdown-toc')
var res = toc('# `API`\n ## [letta](./index.js#L14)\nfoo bar\n## BBB\n## [.promisify](./index.js#L37)\n## CCC\nfoo')

console.log(res.content)

```

**Comment by jonschlinkert** [comment]
Sorry, I know it must be frustrating, I don't put stuff in headings that will be bad for seo so I don't run into these issues. Also I figured exposing the ability to use a custom slugify function would solve this problem. e.g. it "can't be wrong" when you can control the output.

**Comment by tunnckoCore** [comment]
> I don't put stuff in headings that will be bad for seo

Same here. Was just try.

>  it "can't be wrong" when you can control the output.

yeah.
