### ISSUE TITLE
Wrong slug when headline contains &

### ISSUE THREAD

**Issue by dvcrn** [jonschlinkert/markdown-toc#57]
Looks like I found another one 😊 

```
# Hello & World
```

should be

```
hello--world
```

instead of
```
hello-&-world
```

**Comment by jonschlinkert** [comment]
fwiw I went through all of the regex/special characters I could think of and compared behavior to github's actual results. I'll double check but I must have missed this character.

**Comment by jonschlinkert** [comment]
Indeed I did https://github.com/jonschlinkert/markdown-toc/commit/f682e32457a473f01cb1eafcf9d660317b3ae63a#diff-168726dbe96b3ce427e7fedce31bb0bcR202

**Comment by dvcrn** [comment]
Oh I'm sorry for this then! Will check better next time

**Comment by jonschlinkert** [comment]
No, no sorry. When I said "I did", I meant "I did miss this character". You were correct! And thank you again!

**Comment by jonschlinkert** [comment]
fwiw, the diff just shows that I missed the character and just added it per this issue. good thing you created the issue!

**Comment by dvcrn** [comment]
Oh - that's what you get when you take a glimpse at a github issue from your phone. Glad I was able to help. Don't worry, I'll find more 😊
