### ISSUE TITLE
CJK punctuations are omitted in GitHub header anchors

### ISSUE THREAD

**Issue by breeswish** [jonschlinkert/markdown-toc#58]
https://github.com/thlorenz/doctoc/issues/79

**Comment by twang2218** [comment]
@SummerWish Could you provide more details of what's the markdown header exactly, and what is the expected value?

Current implementation will treat the CJK punctuations as is, so if the header is

```markdown
# ，。？
```

And the result would be:

```markdown
- [，。？](#，。？)
```

**Comment by twang2218** [comment]
I created a testing markdown page to test the Github behavior at gist: https://gist.github.com/twang2218/cc1791525b6f06f24cff4266c81c713e#file-test-md

It seems that Github strips most (not all) CJK punctuations, so I created this PR to comply such behavior.
