### ISSUE TITLE
Remarkable plugin causes `.render()` to return an object.

### ISSUE THREAD

**Issue by shannonmoeller** [jonschlinkert/markdown-toc#62]
The [example in the README](https://github.com/jonschlinkert/markdown-toc#tocplugin) of using `toc.plugin()` doesn't seem to work as advertised and I can't for the life of me figure out a workaround.

```js
var Remarkable = require('remarkable');
var toc = require('markdown-toc');

function render(str, options) {
  return new utils.Remarkable()
    .use(toc.plugin(options)) // <= register the plugin
    .render(str);
}
```

The first issue is that `utils` is not defined. Assuming that's a typo and removing it:

```js
var Remarkable = require('remarkable');
var toc = require('markdown-toc');

function render(str, options) {
  return new Remarkable()
    .use(toc.plugin(options))
    .render(str);
}

console.log(render('<!-- toc -->\n\n# A\nfoo\n\n#B\nbar'));
```

I expected something like the following to be logged:

```html
<!-- toc -->
<ul>
    <li><a href="#a">A</a></li>
    <li><a href="#b">B</a></li>
</ul>
<!-- tocstop -->

<h1 id="a">A</h1>
<p>foo</p>
<h1 id="b">B</h1>
<p>bar</p>
```

But I get an object back as though I had invoked `toc()` directly:

```html
[object Object]
```

What am I missing? If I use `toc.insert()`, then pass the result to a `Remarkable` instance, I get the expected toc, but the `<h1>` tags don't have `id` attributes.

**Comment by shannonmoeller** [comment]
As a workaround (or permenant solution if what I described isn't the actual intended use), I've opted to use [`toc`](http://npm.im/toc) on the output instead.

```js
import Remarkable from 'Remarkable';
import highlight from 'highlight.js';
import toc from 'toc';

export function markdown(options) {
    const { fn, hash } = options;
    const md = new Remarkable({
        html: true,

        highlight(code) {
            return highlight.highlightAuto(code).value;
        },

        ...hash,
    });

    return toc.process(md.render(fn(this)), hash);
}
```

**Comment by jonschlinkert** [comment]
`toc()` returns [an object](https://github.com/jonschlinkert/markdown-toc#usage) with a `contents` property, which is a markdown-formatted string. (otherwise, to do what you want the way you're doing it, without looking more closely I think you might need to create a new instance of `Remarkable` before `.render` is called to create the HTML).

my suggestion would be to just use `markdown-toc` directly to get the toc string, then pass that to `.render()`

```js
var Remarkable = require('remarkable');
var toc = require('..');

function convert(str) {
  var md = new Remarkable();
  // optionally override 'open' and 'close' toc delimiters, since we won't need them in HTML
  var res = toc.insert(str, {open: '', close: ''});
  return md.render(res);
}
```

The `h1` ids seems like a different issue IMO. I can show you how to customize the h1 tags or any other tag if you want to open another issue. 

let me know if this works for you

**Comment by shannonmoeller** [comment]
Thanks for the feedback. I played around with a few options. I think I'm still going to settle on using `toc` as a standalone step since my target output is HTML, not a README.md. That ends up being a better pattern in the long run as I can mix and match more freely in my handlebars templates.

```js
import Remarkable from 'Remarkable';
import highlight from 'highlight.js';
import tableOfContents from 'toc';

export function markdown(options) {
    const { fn, hash } = options;
    const md = new Remarkable({
        html: true,
        ...hash,
    });

    return md.render(fn(this));
}

export function toc(options) {
    const { fn, hash } = options;

    return tableOfContents.process(fn(this), hash);
}
```

Thanks again!

**Comment by jonschlinkert** [comment]
great, glad you figured out a solution that works for you!

**Comment by mootari** [comment]
This caught me off-guard as well. markdown-toc could possibly override .toString() on the object:
```javascript
res.toString = function() {
  return this.content;
};
return res;
```
For assemble / templates Views this would still require casting to string:
```javascript
file.content = '' + md.render(file.content);
```
