### ISSUE TITLE
HTML entities should be stripped completely from link targets

### ISSUE THREAD

**Issue by Banbury** [jonschlinkert/markdown-toc#74]
If a heading contains HTML entities (e.g. `&gt;`) only the `&` and the `;` are stripped from the target URL. The text in-between is added to the link.

`<test>` is rendered as `lttestgt`, but should be `test`. The generated link is not valid.

**Comment by jonschlinkert** [comment]
Can you point to a link on the commonmark spec to help save some time? Where is this specified?

**Comment by Banbury** [comment]
I don't know about the spec. But if I convert the markdown to HTML, the links are wrong.

I'm using gitbook. And it removes the entities from the links.

**Comment by jonschlinkert** [comment]
Ok, I just need more information to be able to fix it correctly. I can look into it

**Comment by jonschlinkert** [comment]
I'm about to fix this, but it occurred to me that if `<test>` is defined, we should either retain the entire tag, or strip the entire tag. It makes no sense to keep `test`, given that something like `<div>` would result in `div` being rendered. for now, I'm going to strip the entire tag. We can make this optional if there is a reason to do so.

**Comment by Banbury** [comment]
If you strip 'test', then the link will be wrong nonetheless.

**Comment by jonschlinkert** [comment]
Meaning `<test>`? Did you look at the unit tests? Or check how GitHub does this? Or commonmark?
