### ISSUE TITLE
Typo in README.

### ISSUE THREAD

**Issue by quadrupleslap** [jonschlinkert/markdown-toc#78]
"Highights"

**Comment by jonschlinkert** [comment]
thanks, want to do a pr? or I can fix, thanks

**Comment by Daniel-Mietchen** [comment]
pr is at https://github.com/jonschlinkert/markdown-toc/pull/79 .

**Comment by levithomason** [comment]
#79 has been merged, this can probably be closed.

**Comment by doowb** [comment]
Thanks @Daniel-Mietchen for the PR.
Thanks @levithomason for the reminder.
