### ISSUE TITLE
`querystring.escape is not a function`

### ISSUE THREAD

**Issue by Relequestual** [jonschlinkert/markdown-toc#82]
Hi,

I've followed the advice found at #39 and #44.
I managed to get unlazy-loader to work.

The error appears to be coming from function linkify in index.js.
`Uncaught TypeError: querystring.escape is not a function`

I don't see `querystring` listed as a dependancy. I tried to install it but it had no effect.

**Comment by doowb** [comment]
@Relequestual `querystring` is a built-in module in node. If that's not getting included, there's probably something else that needs to be done in your webpack configuration.

**Comment by jonschlinkert** [comment]
strange that querystring is causing an issue since it's a built-in. Have you found any other webpack issues related to querysting?

**Comment by Relequestual** [comment]
> ...there's probably something else that needs to be done in your webpack configuration.

@doowb Yeah, probably, but I'm new to this, and it's a forked project, and I have decided to try a using a different module because this drove me to crazy.

**Comment by Relequestual** [comment]
@jonschlinkert I personally haven't had any other issues. I found https://github.com/mhart/aws4/issues/46 but the solution offered didn't work in my situation. I have no one local I can ask for support on this =/ markdown-toc is causing too many problems when trying to use webpack, which makes it unuseable for me.

**Comment by jonschlinkert** [comment]
> I personally haven't had any other issues

I was asking if webpack had other existing issues on that repository. 

Sorry webpack is causing so many problems with markdown-toc. There is no technical reason that markdown-toc won't work. 

Closing this since it sounds like you've moved on and this is related to webpack bugs anyway.

**Comment by Relequestual** [comment]
@jonschlinkert A webpack bug? Can you link me to the issue on their repo?

I didn't even realise such an issue could exist. The problem seems to be primeraily caused by lazy-cache.

Is this module primeraily not designed to be used with webpack?

Sure, I may have moved on in terms of spending a few days trying to fix it is not going to work for me, but I'd like to see if I can help get it resolved for the next person who comes along!

**Comment by jonschlinkert** [comment]
> A webpack bug? Can you link me to the issue on their repo?

Nope, that's all you I'm afraid. I can help you with issues on this library. But you'll have to do your own research on the bug you're having from other libraries. 

> The problem seems to be primeraily caused by lazy-cache.

Might seem that way, but no, it's not. 

> but I'm new to this, and it's a forked project

We have quite a bit of experience with this (also keeping in mind that @doowb created the webpack plugin that you mentioned trying). I'm afraid this is definitely a webpack issue. there isn't much more I can say about it. 

@doowb do you have anything to add?

**Comment by doowb** [comment]
If you give a minimum example of the webpack config using the solution you pointed out in `aws4` issue, and the code where you're using `markdown-toc`, it might give us a better idea of what's happening.

> The problem seems to be primeraily caused by lazy-cache.

`querystring` is required in [here](https://github.com/jonschlinkert/markdown-toc/blob/master/index.js#L8) which doesn't have anything to do with `lazy-cache`.

**Comment by Relequestual** [comment]
Thanks @jonschlinkert @doowb.
I Can't make a minimum example right now, but I'll make a note and do so when I can.
@doowb Where is best to file such an issue?

**Comment by zucher** [comment]
I want to use this module, but for the similar failure with reactjs and brunch, I will not :-(
