### ISSUE TITLE
maxdepth from CLI or in <!-- toc --> comment.

### ISSUE THREAD

**Issue by mjhm** [jonschlinkert/markdown-toc#89]
Is there a way to specify the "maxdepth" in the CLI -- or even better would be in the `<!-- toc -->` comment?

**Comment by jonschlinkert** [comment]
I was about to say "yes" b/c I thought I merged in a pr that passes options to the CLI, but it looks like it didn't get published - which wasn't intentional, not sure how I dropped the ball on that. I'll update this issue once that's published, then you should be able to set maxdepth from the CLI.

**Comment by shanehughes3** [comment]
Any update on publication of this feature?

**Comment by sapegin** [comment]
@jonschlinkert How can we help to make it happen? I see a closed PR with this feature — #60. Are you referring to this one?

**Comment by sapegin** [comment]
OK, here is the new PR: https://github.com/jonschlinkert/markdown-toc/pull/95 ;-)

**Comment by doowb** [comment]
`maxdepth` is available through the cli now, thanks @sapegin!
