### ISSUE TITLE
Ignore ToC section in ToC

### ISSUE THREAD

**Issue by RichardLitt** [jonschlinkert/markdown-toc#90]
I have this ToC generated in Sublime using the plugin:

```md
...
## Table of Contents

<!-- TOC depthFrom:2 depthTo:6 withLinks:1 updateOnSave:1 orderedList:0 -->

- [Table of Contents](#table-of-contents)
...
```

Is there a way to not have Table of Contents referred to in the ToC?

**Comment by jonschlinkert** [comment]
> using the plugin:

using what plugin?

**Comment by RichardLitt** [comment]
Huh! My bad! Sorry! This may be the wrong repo. https://github.com/naokazuterada/MarkdownTOC.
